SELECT *
FROM (
    SELECT 
    AI.ANIMAL_ID, AI.NAME
    FROM ANIMAL_INS  AI,
    ANIMAL_OUTS AO 
    WHERE AI.ANIMAL_ID = AO.ANIMAL_ID
    ORDER BY (AO.DATETIME - AI.DATETIME) DESC
) 
WHERE ROWNUM <= 2 -- 제일 바깥에 쓰기
