SELECT 
CRC.CAR_ID,
CRC.CAR_TYPE, 
(CRC.DAILY_FEE * 30) * ((100 - TO_NUMBER(REPLACE(CRP.DISCOUNT_RATE, '%', ''))) / 100)
AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRC,
CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRP
WHERE CRC.CAR_TYPE = CRP.CAR_TYPE
AND CRC.CAR_TYPE IN ('세단', 'SUV')
AND (CRC.DAILY_FEE * 30) * ((100 - TO_NUMBER(REPLACE(CRP.DISCOUNT_RATE, '%', ''))) / 100)
BETWEEN 500000 AND 2000000
AND DURATION_TYPE = '30일 이상'
AND CRC.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221130'
        AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221101'
) 
ORDER BY FEE DESC, CRC.CAR_TYPE, CRC.CAR_ID DESC