SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES 
FROM 
    (
        SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
        FROM REST_INFO
        GROUP BY FOOD_TYPE
    ) T1,
    REST_INFO RI
WHERE T1.FAVORITES = RI.FAVORITES
AND T1.FOOD_TYPE = RI.FOOD_TYPE
ORDER BY RI.FOOD_TYPE DESC