SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FO.AMOUNT * FP.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT FP, FOOD_ORDER FO
WHERE FP.PRODUCT_ID = FO.PRODUCT_ID
AND TO_CHAR(FO.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY FO.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY SUM(FO.AMOUNT * FP.PRICE) DESC, FO.PRODUCT_ID