SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P,
DOCTOR D,
APPOINTMENT A
WHERE A.PT_NO = P.PT_NO
AND D.DR_ID = MDDR_ID
AND APNT_CNCL_YN = FALSE 
AND TO_CHAR(A.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13' 
AND D.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD