SELECT 
UGB.WRITER_ID AS USER_ID, 
UGU.NICKNAME,
SUM(UGB.PRICE) AS TOTAL_SALES
FROM 
USED_GOODS_BOARD UGB,
USED_GOODS_USER UGU
WHERE UGB.WRITER_ID = UGU.USER_ID
AND UGB.STATUS = 'DONE'
GROUP BY UGB.WRITER_ID, UGU.NICKNAME
HAVING SUM(UGB.PRICE) >= 700000
ORDER BY TOTAL_SALES