SELECT RH.CAR_ID
FROM 
CAR_RENTAL_COMPANY_CAR CC,
CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
WHERE CC.CAR_ID = RH.CAR_ID
AND CC.CAR_TYPE = '세단'
AND SUBSTR(TO_CHAR(RH.START_DATE, 'YYYYMMDD'), 5, 2) = '10'
GROUP BY RH.CAR_ID
ORDER BY RH.CAR_ID DESC;
